FROM mcr.microsoft.com/playwright:v1.50.0-noble

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY dist/ ./dist/
COPY viberadar.js ./

ENTRYPOINT ["node", "viberadar.js", "probe", "--watch"]
